# Generated by Django 5.1 on 2025-08-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('degree', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('freelance', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('myimage', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(max_length=50)),
                ('value', models.PositiveIntegerField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
