# Generated by Django 5.1 on 2025-08-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
